export { BioSection } from './BioSection'
export { ContactPriceSection } from './ContactPriceSection'
export { NameSection } from './NameSection'
export { PhotoSection } from './PhotoSection'
export { ServicesSection } from './ServicesSection'
export { SpecializationSection } from './SpecializationSection'
export type { PhotoSectionProps, RegisterOnlyProps, SectionProps } from './types'
